# Generated by Django 5.1.1 on 2025-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqilog',
            name='aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
