# Generated by Django 5.1.1 on 2025-05-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_aqilog_aqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqilog',
            name='aqi',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='co',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='no2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='o3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='pm10',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='pm25',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='so2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
