# Generated by Django 5.1.1 on 2025-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_aqilog_aqi_alter_aqilog_co_alter_aqilog_no2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqilog',
            name='aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='co',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='no2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='o3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='pm10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aqilog',
            name='so2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
