# Generated by Django 5.1.1 on 2025-05-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_aqilog_aqi_alter_aqilog_co_alter_aqilog_no2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedAQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('predicted_aqi', models.FloatField()),
            ],
        ),
    ]
